package api

sealed trait GlobalTranformationType

case object SimilarityTransforms extends GlobalTranformationType
case object RigidTransforms extends GlobalTranformationType
case object NoTransforms extends GlobalTranformationType
